packages:
  - packages/*
allowBuilds:
  '@foundry-rs/anvil': true
  '@foundry-rs/forge': true
  bufferutil: true
  esbuild: true
  keccak: true
  utf-8-validate: true
overrides:
  '@tanstack/react-query': link:../../packages/entrykit/node_modules/@tanstack/react-query
  '@types/react': link:../../packages/entrykit/node_modules/@types/react
  wagmi: link:../../packages/entrykit/node_modules/wagmi
